trigger:
  batch: true
  paths:
    include:
      - src/agents/*

variables:
- name: AZURE_DEVOPS_PAT
  value: '' # no default: override when queueing

jobs:
- template: templates/deploy-image.yaml
  parameters:
    os: 'windows'
    os_tag: 'Windows_NT'
    toolchain: 'dotnet-core'
    toolchain_version: '2.2'
- template: templates/deploy-image.yaml
  parameters:
    os: 'linux'
    toolchain: 'angular'
    toolchain_version: 'ng'
