trigger:
  batch: true
  paths:
    include:
      - src/agents/*

variables:
- name: AZURE_DEVOPS_PAT
  value: 'invalid-PAT@pipeline' # no default: override when queueing

jobs:
- job: DEBUG
  steps:
  - script: echo PAT = $(AZURE_DEVOPS_PAT). Env var = %AZURE_DEVOPS_PAT%
    condition: eq(variables['agent.os'], 'Windows_NT')
  - script: echo PAT = $(AZURE_DEVOPS_PAT). Env var = $AZURE_DEVOPS_PAT
    condition: in(variables['agent.os'], 'Darwin', 'Linux')
- template: templates/deploy-image.yaml
  parameters:
    os: 'windows'
    os_tag: 'Windows_NT'
    toolchain: 'dotnet-core'
    toolchain_version: '2.2'
- template: templates/deploy-image.yaml
  parameters:
    os: 'linux'
    toolchain: 'angular'
    toolchain_version: 'ng'
